version: "3"

server:
  command: "php worker.php"
  env:
    - TEMPORAL_CLI_ADDRESS: temporal:7233

temporal:
  address: ${TEMPORAL_HOST:-localhost}:${TEMPORAL_PORT:-7233}
  activities:
    num_workers: 1

logs:
  level: info
